Repository MaximeHouis/YEP_project1_2019, pull requests merged in 2020-04, with the labels that each got.

#7 Ray lib encapsulation
  Engine/CMakeLists.txt
  Engine/include/Engine/Ray/Ray.hpp
  Engine/include/Engine/Vector/Vector2.hpp
  Engine/include/Engine/Vector/Vector3.hpp
  Engine/include/Engine/Window/Window.hpp
  Engine/src/Ray/Ray.cpp
  Engine/src/Vector/Vector2.cpp
  Engine/src/Vector/Vector3.cpp
  RayTracer/src/test.cpp
  Tests/src/TestsVector2.cpp
  Tests/src/TestsVector3.cpp
Labels: enhancement

#18 Implement Thread pools
  Engine/CMakeLists.txt
  Engine/include/Engine/ThreadPool.hpp
  RayTracer/CMakeLists.txt
  RayTracer/src/Main.cpp
Labels: 0.5 J/H

#25 Migrate test main to Application
  .gitattributes
  CMakeLists.txt
  Engine/src/Application.cpp
  RayTracer/CMakeLists.txt
  RayTracer/include/RayTracerApp.hpp
  RayTracer/src/Main.cpp
  RayTracer/src/RayTracerApp.cpp
Labels: 0.5 J/H

#27 Add Material interface, glass and VentaBlack
  Engine/include/Engine/ThreadPool.hpp
  Engine/src/Assets/Material.cpp
  RayTracer/CMakeLists.txt
  RayTracer/include/Materials/Glass.hpp
  RayTracer/include/Materials/IMaterial.hpp
  RayTracer/src/Materials/Glass.cpp
  RayTracer/src/Materials/IMaterial.cpp
  RayTracer/src/Materials/VentaBlack.cpp
  RayTracer/src/Materials/VentaBlack.hpp
Labels: 0.5 J/H

#28 ADD diffuse material
  RayTracer/include/Objects/Sphere.hpp
  RayTracer/include/RayTracerApp.hpp
  RayTracer/src/RayTracerApp.cpp
Labels: 1 J/H

#29 Fix ThreadPool argument count
  Engine/include/Engine/ThreadPool.hpp
  RayTracer/CMakeLists.txt
  RayTracer/include/Materials/VentaBlack.hpp
  RayTracer/src/Materials/Glass.cpp
  RayTracer/src/Materials/VentaBlack.cpp
Labels: 0.25 J/H

#30 Add scene loading
  Engine/include/Engine/Vector/Vector3.hpp
  Engine/src/Application.cpp
  Engine/src/Vector/Vector3.cpp
  RayTracer/CMakeLists.txt
  RayTracer/include/Materials/Normal.hpp
  RayTracer/include/Objects/Object.hpp
  RayTracer/include/Objects/ObjectList.hpp
  RayTracer/include/Objects/Sphere.hpp
  RayTracer/include/RayTracerApp.hpp
  RayTracer/include/Scene/Scene.hpp
  RayTracer/src/Materials/Normal.cpp
  RayTracer/src/Objects/Object.cpp
  RayTracer/src/RayTracerApp.cpp
  RayTracer/src/Scene/Scene.cpp
  Resources/scene.txt
Labels: 2 J/H

#32 Optimize Random and ThreadPool
  Engine/CMakeLists.txt
  Engine/include/Engine/Application.hpp
  Engine/include/Engine/Raylib.hpp
  Engine/include/Engine/Raymath.hpp
  Engine/include/Engine/Utils/ArgumentParser.hpp
  Engine/include/Engine/Utils/OS.hpp
  Engine/include/Engine/Utils/Random.hpp
  Engine/include/Engine/Utils/ThreadPool.hpp
  Engine/include/Engine/Vector/Vector3.hpp
  Engine/src/Application.cpp
  Engine/src/Utils/ArgumentParser.cpp
  Engine/src/Utils/Random.cpp
  RayTracer/include/Objects/Sphere.hpp
  RayTracer/include/RayTracerApp.hpp
  RayTracer/src/RayTracerApp.cpp
  Tests/src/TestsArgumentParser.cpp
Labels: 1.5 J/H

#36 Material fuze obj
  RayTracer/CMakeLists.txt
  RayTracer/include/Materials/AMaterial.hpp
  RayTracer/include/Materials/Glass.hpp
  RayTracer/include/Materials/Normal.hpp
  RayTracer/include/Materials/VentaBlack.hpp
  RayTracer/include/Objects/Object.hpp
  RayTracer/include/Objects/ObjectList.hpp
  RayTracer/include/Objects/Sphere.hpp
  RayTracer/include/Scene/Scene.hpp
  RayTracer/src/Materials/AMaterial.cpp
  RayTracer/src/Materials/Glass.cpp
  RayTracer/src/Materials/IMaterial.cpp
  RayTracer/src/Materials/Normal.cpp
  RayTracer/src/Materials/VentaBlack.cpp
  RayTracer/src/Objects/Object.cpp
  RayTracer/src/Objects/Sphere.cpp
  RayTracer/src/RayTracerApp.cpp
  RayTracer/src/Scene/Scene.cpp
  Resources/scene.txt
Labels: 1.5 J/H

#41 Rework scene loading: use json files
  .gitignore
  CMakeLists.txt
  RayTracer/include/Materials/AMaterial.hpp
  RayTracer/include/Materials/Glass.hpp
  RayTracer/include/Materials/Metal.hpp
  RayTracer/include/Materials/Normal.hpp
  RayTracer/include/Materials/VentaBlack.hpp
  RayTracer/include/Scene/Scene.hpp
  RayTracer/src/Materials/AMaterial.cpp
  RayTracer/src/Materials/Glass.cpp
  RayTracer/src/Materials/Metal.cpp
  RayTracer/src/Materials/Normal.cpp
  RayTracer/src/Materials/VentaBlack.cpp
  RayTracer/src/Scene/Scene.cpp
  Resources/scene.json
  Resources/scene.txt
Labels: 1 J/H

#45 Optimize rendering
  Engine/CMakeLists.txt
  Engine/include/Engine/Application.hpp
  Engine/include/Engine/Vector/Vector3.hpp
  Engine/src/Application.cpp
  RayTracer/include/Objects/Sphere.hpp
  RayTracer/include/RayTracerApp.hpp
  RayTracer/src/Main.cpp
  RayTracer/src/Objects/Sphere.cpp
  RayTracer/src/RayTracerApp.cpp
  Resources/scene.json
  SceneEditor/src/Main.cpp
Labels: 2 J/H

#51 Improve Camera
  RayTracer/CMakeLists.txt
  RayTracer/include/Camera/Camera.hpp
  RayTracer/src/Camera/Camera.cpp
  RayTracer/src/RayTracerApp.cpp
Labels: 2 J/H

#53 Add LightMaterial
  Engine/include/Engine/Utils/Random.hpp
  RayTracer/CMakeLists.txt
  RayTracer/include/Materials/AMaterial.hpp
  RayTracer/include/Materials/Light.hpp
  RayTracer/src/Materials/Light.cpp
  RayTracer/src/RayTracerApp.cpp
  RayTracer/src/Scene/Scene.cpp
Labels: 1.5 J/H

#54 Add camera JSON config
  RayTracer/include/RayTracerApp.hpp
  RayTracer/include/Scene/Scene.hpp
  RayTracer/src/RayTracerApp.cpp
  RayTracer/src/Scene/Scene.cpp
  Resources/scene.json
Labels: 0.5 J/H

#55 Remove Scene Editor
  CMakeLists.txt
  SceneEditor/CMakeLists.txt
  SceneEditor/include/Raygui.hpp
  SceneEditor/include/SceneEditorApp.hpp
  SceneEditor/src/Main.cpp
  SceneEditor/src/SceneEditorApp.cpp
Labels: 0 J/H

#57 Export generated images to a directory
  .gitignore
  RayTracer/include/RayTracerApp.hpp
  RayTracer/src/RayTracerApp.cpp
  Resources/scene.json
Labels: 0.5 J/H

#59 Add a new scene
  RayTracer/src/RayTracerApp.cpp
  Resources/cool_scene.json
Labels: 0.5 J/H

#49 Add glass material draft
  Engine/CMakeLists.txt
  Engine/include/Engine/Raymath.hpp
  Engine/include/Engine/Utils/ArgumentParser.hpp
  Engine/include/Engine/Utils/Calcul.hpp
  Engine/include/Engine/Utils/OS.hpp
  Engine/include/Engine/Utils/Operations.hpp
  Engine/src/Utils/Operations.cpp
  RayTracer/include/Camera/Camera.hpp
  RayTracer/include/Materials/AMaterial.hpp
  RayTracer/include/Materials/Glass.hpp
  RayTracer/include/Materials/Light.hpp
  RayTracer/include/Materials/Metal.hpp
  RayTracer/include/Materials/Normal.hpp
  RayTracer/include/Materials/VentaBlack.hpp
  RayTracer/src/Camera/Camera.cpp
  RayTracer/src/Materials/AMaterial.cpp
  RayTracer/src/Materials/Glass.cpp
  RayTracer/src/Materials/Light.cpp
  RayTracer/src/Materials/Metal.cpp
  RayTracer/src/Materials/Normal.cpp
  RayTracer/src/Materials/VentaBlack.cpp
  RayTracer/src/RayTracerApp.cpp
  Resources/scene.json
Labels: 3 J/H
